#!/usr/bin/env bash
# Regenerate skills/core/fable-mode/references/ from the standalone skills.
#
# fable-mode is self-contained: it embeds the full text of every skill it routes
# to, so it works even when nothing else is installed. That means the reference
# copies must be generated, never hand-edited — edit the source SKILL.md instead
# and re-run this.
#
#   bash scripts/sync-references.sh

set -euo pipefail

cd "$(dirname "$0")/.."

REFS="skills/core/fable-mode/references"
rm -rf "$REFS"
mkdir -p "$REFS"

INDEX="$REFS/INDEX.md"

cat > "$INDEX" <<'EOF'
# Embedded reference library

Generated by `scripts/sync-references.sh`. **Do not edit these files** — edit the
source `SKILL.md` and re-run the script.

`fable-mode` routes to the specialist skills below. If the skill is installed,
invoke it normally. If it is not, `read` the reference here and apply the process
inline — that is what makes `fable-mode` self-contained.

| Skill | Reference |
|---|---|
EOF

# Every skill except fable-mode itself.
find skills -name SKILL.md -not -path '*/fable-mode/*' | sort | while read -r skill; do
  name="$(basename "$(dirname "$skill")")"
  cp "$skill" "$REFS/$name.md"
  printf '| `/%s` | [%s.md](%s.md) |\n' "$name" "$name" "$name" >> "$INDEX"
done

count=$(find "$REFS" -name '*.md' -not -name INDEX.md | wc -l | tr -d ' ')
echo "Synced $count references into $REFS"
